services:
  docker_db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: edupage-web
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_docker:/var/lib/postgresql
    ports:
      - "5433:5432"
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - docker_db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://docker_db:5432/postgres"
      JAVA_OPTS: "-Xmx512m"
volumes:
  pg_docker:
